// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package ma.projet.grpc.stubs;

public interface DeleteCompteByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteCompteByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Message de confirmation
   * </pre>
   *
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Message de confirmation
   * </pre>
   *
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
