// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package ma.projet.grpc.stubs;

public interface GetComptesByTypeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetComptesByTypeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Type de compte (COURANT ou EPARGNE)
   * </pre>
   *
   * <code>.TypeCompte type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * Type de compte (COURANT ou EPARGNE)
   * </pre>
   *
   * <code>.TypeCompte type = 1;</code>
   * @return The type.
   */
  ma.projet.grpc.stubs.TypeCompte getType();
}
